sudo: required
services:
    - docker

before_install:
  - docker build -t kono10/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kono10/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'docker-new'
  env: 'DockerNew-env'
  bucket_name: 'elasticbeanstalk-us-east-2-627041391177'
  bucket_path: 'docker-new'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
